title: Tailscale on Raspberry Pi
description: Step-by-step guide to setting up Tailscale and a secure VPN exit node on Raspberry Pi.
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
include:
  - assets
plugins:
  - jekyll-seo-tag
image: /assets/images/social-card.png